import {
  Product,
  Order,
  ReturnRecord,
  Settlement,
  Claim,
  Supplier,
  PurchaseBill,
  Expense,
  AIStagedDocument,
  FinancialAuditLog,
  CustomerComplaint,
  UserAccount,
} from "./types";
import { validateDocumentArithmetic } from "./guardrails";

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: "SUP-001",
    name: "Apex Electronics Mfg Ltd",
    contactPerson: "Rajesh Sharma",
    email: "orders@apexelectronics.in",
    phone: "+91 98200 12345",
    gstin: "27AAACA1234A1Z5",
    address: "Bhiwandi Industrial Area, Thane, Maharashtra",
    paymentTerms: "Net 30",
    bankAccount: "HDFC Bank - A/C 50200088912 (IFSC: HDFC0000123)",
    upiId: "apex.mfg@okhdfcbank",
    openingBalance: 0,
    totalPaid: 44840,
    notes: "Primary supplier for audio & wireless peripherals.",
  },
  {
    id: "SUP-002",
    name: "Zenith Cable & Power Supplies",
    contactPerson: "Vikram Mehta",
    email: "supply@zenithpower.co.in",
    phone: "+91 99300 67890",
    gstin: "24AABCS5678B1Z2",
    address: "GIDC Industrial Estate, Ahmedabad, Gujarat",
    paymentTerms: "Net 15",
    bankAccount: "ICICI Bank - A/C 001205009871 (IFSC: ICIC0000012)",
    upiId: "zenithpower@okicici",
    openingBalance: 0,
    totalPaid: 24780,
    notes: "Supplier for chargers, cables, and adaptors.",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "PROD-01",
    sku: "ELEC-WEM-01",
    mfn: "MFN-WEM-010",
    mfn1: "MFN1-WEM-010-A",
    name: "Wireless Ergonomic Mouse (Silent Click)",
    category: "Computer Peripherals",
    brand: "VoltTech",
    currentCostPrice: 380,
    supplierId: "SUP-001",
    active: true,
    stockQuantity: 92,
    channelAliases: {
      "Amazon India": "B08WEM01-IND",
      Flipkart: "FLIP-MOUSE-WEM",
      Meesho: "MSHO-98311-MSE",
      "Personal Website": "VT-WEM-01",
    },
    costHistory: [
      {
        validFrom: "2026-01-01",
        validTo: "2026-03-31",
        costPrice: 320,
        notes: "Initial batch Q1 import contract",
      },
      {
        validFrom: "2026-04-01",
        validTo: "2026-07-31",
        costPrice: 350,
        notes: "Raw material plastic & chip price adjustment",
      },
      {
        validFrom: "2026-08-01",
        costPrice: 380,
        notes: "Current active purchasing cost",
      },
    ],
  },
  {
    id: "PROD-02",
    sku: "ELEC-USBC-65W",
    mfn: "MFN-CHG-065",
    mfn1: "MFN1-CHG-065-B",
    name: "65W GaN Fast Charger (Dual USB-C)",
    category: "Mobile Accessories",
    brand: "VoltTech",
    currentCostPrice: 420,
    supplierId: "SUP-002",
    active: true,
    stockQuantity: 46,
    channelAliases: {
      "Amazon India": "B09GAN65W-BLK",
      Flipkart: "FLIP-CHG-65W",
      Meesho: "MSHO-7721-CHG",
      "Personal Website": "VT-CHG-65W",
    },
    costHistory: [
      {
        validFrom: "2026-01-01",
        validTo: "2026-05-31",
        costPrice: 390,
        notes: "Bulk contract Q1-Q2",
      },
      {
        validFrom: "2026-06-01",
        costPrice: 420,
        notes: "Semiconductor revision",
      },
    ],
  },
  {
    id: "PROD-03",
    sku: "ELEC-ANC-EB",
    mfn: "MFN-ANC-900",
    mfn1: "MFN1-ANC-900-C",
    name: "Active Noise Cancelling TWS Earbuds",
    category: "Audio",
    brand: "VoltTech",
    currentCostPrice: 840,
    supplierId: "SUP-001",
    active: true,
    stockQuantity: 38,
    channelAliases: {
      "Amazon India": "B07TWSANC-PRO",
      Flipkart: "FLIP-TWS-ANC01",
      Meesho: "MSHO-5541-TWS",
      "Personal Website": "VT-ANC-01",
    },
    costHistory: [
      {
        validFrom: "2026-01-01",
        validTo: "2026-04-30",
        costPrice: 780,
        notes: "Launch batch pricing",
      },
      {
        validFrom: "2026-05-01",
        costPrice: 840,
        notes: "Enhanced driver component cost",
      },
    ],
  },
  {
    id: "PROD-04",
    sku: "ELEC-BRAID-CBL",
    mfn: "MFN-CBL-100",
    mfn1: "MFN1-CBL-100-D",
    name: "Braided 100W Type-C to Type-C Cable (2m)",
    category: "Cables",
    brand: "VoltTech",
    currentCostPrice: 110,
    supplierId: "SUP-002",
    active: true,
    stockQuantity: 185,
    channelAliases: {
      "Amazon India": "B08CBL100W-2M",
      Flipkart: "FLIP-CBL-100W",
      Meesho: "MSHO-1102-CBL",
      "Personal Website": "VT-CBL-100W",
    },
    costHistory: [
      {
        validFrom: "2026-01-01",
        costPrice: 110,
        notes: "Steady raw material pricing",
      },
    ],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ORD-0994",
    channelOrderId: "OD8839201928410294",
    marketplace: "Flipkart",
    orderDate: "2026-08-26",
    status: "CLAIM_APPROVED",
    customerName: "Rakesh Verma",
    customerCity: "Kanpur",
    customerState: "Uttar Pradesh",
    shippingFeeCharged: 40,
    marketplaceChargesEstimate: 160,
    settlementAmount: 0,
    settlementPercent: 0,
    items: [
      {
        id: "ITEM-094",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 1,
        sellingPrice: 1299,
        discount: 0,
        taxAmount: 198.15,
        snapshotUnitCost: 420,
        returnedQuantity: 1,
      },
    ],
    returnIds: ["RET-203"],
    claimIds: ["CLM-302"],
  },
  {
    id: "ORD-WHL-501",
    channelOrderId: "CHALLAN-BLR-882",
    marketplace: "B2B Wholesale",
    orderDate: "2026-09-10",
    status: "CUSTOMER_RETURN",
    customerName: "Metro Retail Distribution",
    customerCity: "Bengaluru",
    customerState: "Karnataka",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 0,
    settlementAmount: 0,
    settlementPercent: 0,
    items: [
      {
        id: "ITEM-WHL-01",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 10,
        sellingPrice: 899,
        discount: 0,
        taxAmount: 1370,
        snapshotUnitCost: 380,
        returnedQuantity: 10,
      },
    ],
    returnIds: ["RET-204"],
  },
  {
    id: "ORD-0998",
    channelOrderId: "402-1829301-4492019",
    marketplace: "Amazon India",
    orderDate: "2026-08-18",
    status: "DELIVERED",
    customerName: "Vikram Malhotra",
    customerCity: "Gurugram",
    customerState: "Haryana",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 145,
    items: [
      {
        id: "ITEM-098",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 1,
        sellingPrice: 899,
        discount: 50,
        taxAmount: 129.5,
        snapshotUnitCost: 380,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-AZ-901"],
  },
  {
    id: "ORD-0999",
    channelOrderId: "OD8829104910293812",
    marketplace: "Flipkart",
    orderDate: "2026-08-25",
    status: "DELIVERED",
    customerName: "Pooja Hegde",
    customerCity: "Chennai",
    customerState: "Tamil Nadu",
    shippingFeeCharged: 40,
    marketplaceChargesEstimate: 210,
    items: [
      {
        id: "ITEM-099",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 1,
        sellingPrice: 1299,
        discount: 100,
        taxAmount: 182.9,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-FK-401"],
  },
  {
    id: "ORD-1001",
    channelOrderId: "402-8392182-1928301",
    marketplace: "Amazon India",
    orderDate: "2026-09-02",
    status: "DELIVERED",
    customerName: "Aarav Patel",
    customerCity: "Bengaluru",
    customerState: "Karnataka",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 145,
    items: [
      {
        id: "ITEM-101",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 1,
        sellingPrice: 899,
        discount: 50,
        taxAmount: 129.5,
        snapshotUnitCost: 380, // Locked at order creation
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-AZ-901"],
  },
  {
    id: "ORD-1002",
    channelOrderId: "OD3289192839182390",
    marketplace: "Flipkart",
    orderDate: "2026-09-03",
    status: "DELIVERED",
    customerName: "Sneha Reddy",
    customerCity: "Hyderabad",
    customerState: "Telangana",
    shippingFeeCharged: 40,
    marketplaceChargesEstimate: 210,
    items: [
      {
        id: "ITEM-102",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 1,
        sellingPrice: 1299,
        discount: 100,
        taxAmount: 182.9,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-FK-401"],
  },
  {
    id: "ORD-1003",
    channelOrderId: "MSH-992104-B",
    marketplace: "Meesho",
    orderDate: "2026-09-03",
    status: "RTO",
    customerName: "Rohan Das",
    customerCity: "Patna",
    customerState: "Bihar",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 65,
    items: [
      {
        id: "ITEM-103",
        sku: "ELEC-BRAID-CBL",
        productName: "Braided 100W Type-C to Type-C Cable (2m)",
        quantity: 2,
        sellingPrice: 299,
        discount: 0,
        taxAmount: 45.6,
        snapshotUnitCost: 110,
        returnedQuantity: 2,
      },
    ],
    returnIds: ["RET-201"],
  },
  {
    id: "ORD-1004",
    channelOrderId: "WEB-2026-8819",
    marketplace: "Personal Website",
    orderDate: "2026-09-04",
    status: "DELIVERED",
    customerName: "Kavita Nair",
    customerCity: "Kochi",
    customerState: "Kerala",
    shippingFeeCharged: 50,
    marketplaceChargesEstimate: 42, // Payment gateway fee 2%
    items: [
      {
        id: "ITEM-104",
        sku: "ELEC-ANC-EB",
        productName: "Active Noise Cancelling TWS Earbuds",
        quantity: 1,
        sellingPrice: 2199,
        discount: 200,
        taxAmount: 305,
        snapshotUnitCost: 840,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-WEB-101"],
  },
  {
    id: "ORD-1005",
    channelOrderId: "405-1920394-8291032",
    marketplace: "Amazon India",
    orderDate: "2026-09-04",
    status: "PARTIALLY_RETURNED",
    customerName: "Vikram Singhania",
    customerCity: "Mumbai",
    customerState: "Maharashtra",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 340,
    items: [
      {
        id: "ITEM-105A",
        sku: "ELEC-ANC-EB",
        productName: "Active Noise Cancelling TWS Earbuds",
        quantity: 2,
        sellingPrice: 2199,
        discount: 100,
        taxAmount: 650,
        snapshotUnitCost: 840,
        returnedQuantity: 1, // 1 returned out of 2 (Partial Return Demo)
      },
      {
        id: "ITEM-105B",
        sku: "ELEC-BRAID-CBL",
        productName: "Braided 100W Type-C to Type-C Cable (2m)",
        quantity: 1,
        sellingPrice: 349,
        discount: 0,
        taxAmount: 53.2,
        snapshotUnitCost: 110,
        returnedQuantity: 0,
      },
    ],
    returnIds: ["RET-202"],
    claimIds: ["CLM-301"],
    settlementIds: ["SET-AZ-902"],
  },
  {
    id: "ORD-1006",
    channelOrderId: "OD9920193820192841",
    marketplace: "Flipkart",
    orderDate: "2026-09-05",
    status: "SHIPPED",
    customerName: "Priya Sharma",
    customerCity: "Jaipur",
    customerState: "Rajasthan",
    shippingFeeCharged: 40,
    marketplaceChargesEstimate: 160,
    items: [
      {
        id: "ITEM-106",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 1,
        sellingPrice: 949,
        discount: 50,
        taxAmount: 137,
        snapshotUnitCost: 380,
        returnedQuantity: 0,
      },
    ],
  },
  {
    id: "ORD-1007",
    channelOrderId: "MSH-110294-A",
    marketplace: "Meesho",
    orderDate: "2026-09-05",
    status: "DELIVERED",
    customerName: "Mohd. Tariq",
    customerCity: "Lucknow",
    customerState: "Uttar Pradesh",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 38,
    items: [
      {
        id: "ITEM-107",
        sku: "ELEC-BRAID-CBL",
        productName: "Braided 100W Type-C to Type-C Cable (2m)",
        quantity: 3,
        sellingPrice: 289,
        discount: 30,
        taxAmount: 127.8,
        snapshotUnitCost: 110,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-MSH-001"],
  },
  {
    id: "ORD-1008",
    channelOrderId: "MYN-994182901",
    marketplace: "Myntra",
    orderDate: "2026-09-06",
    status: "DELIVERED",
    customerName: "Ananya Deshmukh",
    customerCity: "Pune",
    customerState: "Maharashtra",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 290,
    items: [
      {
        id: "ITEM-108",
        sku: "ELEC-ANC-EB",
        productName: "Active Noise Cancelling TWS Earbuds",
        quantity: 1,
        sellingPrice: 1999,
        discount: 150,
        taxAmount: 281.8,
        snapshotUnitCost: 840,
        returnedQuantity: 0,
      },
    ],
  },
  {
    id: "ORD-1009",
    channelOrderId: "WC-881920",
    marketplace: "WooCommerce",
    orderDate: "2026-09-07",
    status: "CONFIRMED",
    customerName: "Kunal Mehra",
    customerCity: "Delhi",
    customerState: "Delhi",
    shippingFeeCharged: 50,
    marketplaceChargesEstimate: 45,
    items: [
      {
        id: "ITEM-109",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 2,
        sellingPrice: 1199,
        discount: 0,
        taxAmount: 365.8,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
  },
  {
    id: "ORD-1010",
    channelOrderId: "402-9981240-1928401",
    marketplace: "Amazon India",
    orderDate: "2026-09-06",
    status: "DELIVERED",
    customerName: "Divya Kapoor",
    customerCity: "Delhi",
    customerState: "Delhi",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 195,
    items: [
      {
        id: "ITEM-110",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 1,
        sellingPrice: 1299,
        discount: 50,
        taxAmount: 182.9,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-AZ-903"],
  },
  {
    id: "ORD-1011",
    channelOrderId: "OD7728192019482710",
    marketplace: "Flipkart",
    orderDate: "2026-09-06",
    status: "DELIVERED",
    customerName: "Arjun Rampal",
    customerCity: "Ahmedabad",
    customerState: "Gujarat",
    shippingFeeCharged: 40,
    marketplaceChargesEstimate: 290,
    items: [
      {
        id: "ITEM-111",
        sku: "ELEC-ANC-EB",
        productName: "Active Noise Cancelling TWS Earbuds",
        quantity: 1,
        sellingPrice: 2199,
        discount: 150,
        taxAmount: 305,
        snapshotUnitCost: 840,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-FK-402"],
  },
  {
    id: "ORD-1012",
    channelOrderId: "MYN-778210928",
    marketplace: "Myntra",
    orderDate: "2026-09-05",
    status: "DELIVERED",
    customerName: "Siddharth Verma",
    customerCity: "Mumbai",
    customerState: "Maharashtra",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 310,
    items: [
      {
        id: "ITEM-112",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 2,
        sellingPrice: 999,
        discount: 100,
        taxAmount: 279,
        snapshotUnitCost: 380,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-MYN-301"],
  },
  {
    id: "ORD-1013",
    channelOrderId: "MYN-882194012",
    marketplace: "Myntra",
    orderDate: "2026-09-07",
    status: "DELIVERED",
    customerName: "Kritika Soni",
    customerCity: "Jaipur",
    customerState: "Rajasthan",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 185,
    items: [
      {
        id: "ITEM-113",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 1,
        sellingPrice: 1399,
        discount: 50,
        taxAmount: 198.5,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-MYN-302"],
  },
  {
    id: "ORD-1014",
    channelOrderId: "MSH-448192-C",
    marketplace: "Meesho",
    orderDate: "2026-09-06",
    status: "DELIVERED",
    customerName: "Sunil Verma",
    customerCity: "Indore",
    customerState: "Madhya Pradesh",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 42,
    items: [
      {
        id: "ITEM-114",
        sku: "ELEC-WEM-01",
        productName: "Wireless Ergonomic Mouse (Silent Click)",
        quantity: 1,
        sellingPrice: 799,
        discount: 20,
        taxAmount: 114.2,
        snapshotUnitCost: 380,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-MSH-002"],
  },
  {
    id: "ORD-1015",
    channelOrderId: "MSH-552190-D",
    marketplace: "Meesho",
    orderDate: "2026-09-07",
    status: "DELIVERED",
    customerName: "Meenakshi Iyer",
    customerCity: "Coimbatore",
    customerState: "Tamil Nadu",
    shippingFeeCharged: 0,
    marketplaceChargesEstimate: 85,
    items: [
      {
        id: "ITEM-115",
        sku: "ELEC-USBC-65W",
        productName: "65W GaN Fast Charger (Dual USB-C)",
        quantity: 2,
        sellingPrice: 1199,
        discount: 40,
        taxAmount: 350.2,
        snapshotUnitCost: 420,
        returnedQuantity: 0,
      },
    ],
    settlementIds: ["SET-MSH-003"],
  },
];

export const INITIAL_RETURNS: ReturnRecord[] = [
  {
    id: "RET-201",
    orderId: "ORD-1003",
    channelOrderId: "MSH-992104-B",
    marketplace: "Meesho",
    returnDate: "2026-09-05",
    receivedDate: "2026-09-06",
    awbNumber: "FMPP0049281920",
    returnType: "RTO",
    returnReason: "Customer refused delivery / unreachable address",
    sku: "ELEC-BRAID-CBL",
    productName: "Braided 100W Type-C to Type-C Cable (2m)",
    quantity: 2,
    condition: "SELLABLE",
    restockStatus: "PENDING_RESTOCK",
    claimDeadline: "2026-09-12",
    returnShippingCost: 0,
    customerReturnFee: 0, // RTO: return fee = 0
    otherReturnCosts: 0,
    inventoryRecoveryValue: 220, // 2 units @ 110 recovered back to stock
    lossAmount: 0, // RTO has 0 return fee and 0 loss
    notes: "Package returned unopened in original shipper carton.",
  },
  {
    id: "RET-202",
    orderId: "ORD-1005",
    channelOrderId: "405-1920394-8291032",
    marketplace: "Amazon India",
    returnDate: "2026-09-06",
    receivedDate: "2026-09-06",
    awbNumber: "AWB-DEL-9921092",
    returnType: "DAMAGED_RETURN",
    returnReason: "Customer reported defective right earbud; product housing cracked upon receipt",
    sku: "ELEC-ANC-EB",
    productName: "ANC Wireless Earbuds (Active Noise Cancellation)",
    quantity: 1, // Partial return: 1 of 2 ordered
    condition: "DAMAGED",
    restockStatus: "WRITTEN_OFF",
    claimDeadline: "2026-10-06",
    returnShippingCost: 85,
    customerReturnFee: 50, // Customer return: fee always recorded
    otherReturnCosts: 15,
    inventoryRecoveryValue: 100, // Scrap salvage value
    lossAmount: 825, // (Cost 840 - Scrap 100) + Shipping 85 = net loss
    claimId: "CLM-301",
    notes: "Physical damage caused in transit. SAFE-T Claim filed with Amazon.",
  },
  {
    id: "RET-203",
    orderId: "ORD-0994",
    channelOrderId: "OD8839201928410294",
    marketplace: "Flipkart",
    returnDate: "2026-08-28",
    receivedDate: "2026-08-30",
    awbNumber: "EKART-99218201",
    returnType: "CUSTOMER_RETURN",
    returnReason: "Wrong item received complaint by customer; awaiting warehouse verification",
    sku: "ELEC-USBC-65W",
    productName: "65W GaN Fast Charger (Dual USB-C)",
    quantity: 1,
    condition: "UNDER_INSPECTION",
    restockStatus: "PENDING_RESTOCK",
    claimDeadline: "2026-09-11", // Nearing/past Flipkart claim window (Old Return alert)
    returnShippingCost: 65,
    customerReturnFee: 40, // Customer return: fee always recorded
    otherReturnCosts: 10,
    inventoryRecoveryValue: 0,
    lossAmount: 495,
    notes: "Package sitting in uninspected reverse pallet >18 days. Urgent Flipkart dispute claim needed.",
  },
  {
    id: "RET-204",
    orderId: "ORD-WHL-501",
    channelOrderId: "CHALLAN-BLR-882",
    marketplace: "B2B Wholesale",
    returnDate: "2026-09-12",
    receivedDate: "2026-09-14",
    awbNumber: "VRL-LOG-77218",
    returnType: "CUSTOMER_RETURN",
    returnReason: "Retailer returned overstock cartons prior to quarterly inventory refresh",
    sku: "ELEC-WEM-01",
    productName: "Wireless Ergonomic Mouse (Silent Click)",
    quantity: 10,
    condition: "SELLABLE",
    restockStatus: "PENDING_RESTOCK",
    claimDeadline: "2026-10-12",
    returnShippingCost: 180,
    customerReturnFee: 0, // B2B wholesale return, no marketplace return fee
    otherReturnCosts: 20,
    inventoryRecoveryValue: 3800,
    lossAmount: 200,
    notes: "Direct wholesale debit note return. 10 units sealed in original cartons.",
  },
  {
    id: "RET-205",
    orderId: "ORD-1008",
    channelOrderId: "MYN-994182901",
    marketplace: "Myntra",
    returnDate: "2026-09-10",
    receivedDate: "2026-09-12",
    awbNumber: "DELHIVERY-MYN-391",
    returnType: "RTO",
    returnReason: "Customer canceled at doorstep (Doorstep rejection)",
    sku: "ELEC-BRAID-CBL",
    productName: "Braided 100W Type-C to Type-C Cable (2m)",
    quantity: 3,
    condition: "SELLABLE",
    restockStatus: "RESTOCKED",
    claimDeadline: "2026-10-10",
    returnShippingCost: 0,
    customerReturnFee: 0, // RTO: return fee = 0
    otherReturnCosts: 0,
    inventoryRecoveryValue: 330,
    lossAmount: 0, // RTO has 0 return fee and 0 loss
    notes: "Put away back to Bin A-14. Available stock updated.",
  },
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: "CLM-301",
    orderId: "ORD-1005",
    returnId: "RET-202",
    marketplace: "Amazon India",
    claimType: "DAMAGED_INVOICE",
    claimDate: "2026-09-06",
    amountClaimed: 840,
    amountRecovered: 650,
    status: "APPROVED",
    recoveryDate: "2026-09-07",
    notes: "Amazon SAFE-T Claim partially approved (₹650 reimbursement issued).",
    supportingDocuments: ["DOC-SAFE-T-405.pdf"],
  },
  {
    id: "CLM-302",
    orderId: "ORD-0994",
    marketplace: "Flipkart",
    claimType: "LOST_IN_TRANSIT",
    claimDate: "2026-08-28",
    amountClaimed: 1299,
    amountRecovered: 1299,
    status: "RECOVERED",
    recoveryDate: "2026-09-02",
    notes: "Courier lost shipment in transit. 100% claim recovered in settlement.",
  },
  {
    id: "CLM-303",
    orderId: "ORD-1008",
    marketplace: "Myntra",
    claimType: "DAMAGED_INVOICE",
    claimDate: "2026-09-06",
    amountClaimed: 999,
    amountRecovered: 850,
    status: "APPROVED",
    recoveryDate: "2026-09-07",
    notes: "Myntra transit packaging rupture reimbursement approved.",
  },
  {
    id: "CLM-304",
    orderId: "ORD-1003",
    returnId: "RET-201",
    marketplace: "Meesho",
    claimType: "WRONG_RETURN_ITEM",
    claimDate: "2026-09-06",
    amountClaimed: 598,
    amountRecovered: 420,
    status: "APPROVED",
    recoveryDate: "2026-09-07",
    notes: "RTO discrepancy dispute settled by Meesho logistics desk.",
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: "SET-AZ-901",
    settlementBatchId: "AZ-PAY-SEP-W1",
    marketplace: "Amazon India",
    settlementDate: "2026-09-05",
    orderId: "ORD-1001",
    grossAmount: 849,
    deductions: [
      { category: "COMMISSION", name: "Amazon Referral Fee (12%)", amount: 101.88 },
      { category: "FIXED_FEE", name: "Closing Fee", amount: 25 },
      { category: "LOGISTICS", name: "Easy Ship Weight Handling Fee", amount: 48 },
    ],
    tcsTdsTax: 8.49 + 0.85, // TCS 1% + TDS 0.1%
    netSettlement: 664.78,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "CMS-HDFC-98218921",
  },
  {
    id: "SET-FK-401",
    settlementBatchId: "FK-NEFT-2026-09",
    marketplace: "Flipkart",
    settlementDate: "2026-09-06",
    orderId: "ORD-1002",
    grossAmount: 1239,
    deductions: [
      { category: "COMMISSION", name: "Marketplace Commission", amount: 148.68 },
      { category: "LOGISTICS", name: "Ekart Logistics Fee", amount: 62 },
      { category: "COLLECTION_FEE", name: "Prepaid Payment Collection Fee (2%)", amount: 24.78 },
    ],
    tcsTdsTax: 12.39 + 1.24,
    netSettlement: 989.91,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "NEFT-AXIS-0012984",
  },
  {
    id: "SET-AZ-902",
    settlementBatchId: "AZ-PAY-SEP-W1",
    marketplace: "Amazon India",
    settlementDate: "2026-09-07",
    orderId: "ORD-1005",
    grossAmount: 4647,
    deductions: [
      { category: "COMMISSION", name: "Referral Fees", amount: 480 },
      { category: "FIXED_FEE", name: "Closing Fees", amount: 50 },
      { category: "LOGISTICS", name: "Easy Ship Delivery", amount: 95 },
      { category: "RETURN_SHIPPING", name: "Customer Return Fee (RET-202)", amount: 85 },
    ],
    tcsTdsTax: 46.47 + 4.65,
    netSettlement: 3885.88,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "CMS-HDFC-98219999",
  },
  {
    id: "SET-WEB-101",
    settlementBatchId: "RZP-PAYOUT-0904",
    marketplace: "Personal Website",
    settlementDate: "2026-09-05",
    orderId: "ORD-1004",
    grossAmount: 2049,
    deductions: [
      { category: "COLLECTION_FEE", name: "Razorpay Gateway Fee (2% + GST)", amount: 48.36 },
      { category: "LOGISTICS", name: "Shiprocket Surface Delivery", amount: 65 },
    ],
    tcsTdsTax: 0,
    netSettlement: 1935.64,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "RZP-TRANSFER-88123",
  },
  {
    id: "SET-MSH-001",
    settlementBatchId: "MSH-PAY-0906",
    marketplace: "Meesho",
    settlementDate: "2026-09-07",
    orderId: "ORD-1007",
    grossAmount: 837,
    deductions: [
      { category: "COMMISSION", name: "0% Commission Promo", amount: 0 },
      { category: "LOGISTICS", name: "Meesho Logistics Fulfillment", amount: 72 },
    ],
    tcsTdsTax: 8.37 + 0.84,
    netSettlement: 755.79,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "NEFT-ICICI-4412",
  },
  {
    id: "SET-AZ-903",
    settlementBatchId: "AZ-PAY-SEP-W2",
    marketplace: "Amazon India",
    settlementDate: "2026-09-07",
    orderId: "ORD-1010",
    grossAmount: 1249,
    deductions: [
      { category: "COMMISSION", name: "Amazon Referral Fee (10%)", amount: 124.9 },
      { category: "FIXED_FEE", name: "Closing Fee", amount: 25 },
      { category: "LOGISTICS", name: "Easy Ship Weight Handling Fee", amount: 45 },
    ],
    tcsTdsTax: 12.49 + 1.25,
    netSettlement: 1040.36,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "CMS-HDFC-9941021",
  },
  {
    id: "SET-FK-402",
    settlementBatchId: "FK-NEFT-2026-09B",
    marketplace: "Flipkart",
    settlementDate: "2026-09-07",
    orderId: "ORD-1011",
    grossAmount: 2089,
    deductions: [
      { category: "COMMISSION", name: "Marketplace Commission", amount: 208.9 },
      { category: "LOGISTICS", name: "Ekart Logistics Fee", amount: 80 },
      { category: "COLLECTION_FEE", name: "Prepaid Collection Fee", amount: 41.78 },
    ],
    tcsTdsTax: 20.89 + 2.09,
    netSettlement: 1735.34,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "NEFT-AXIS-99210",
  },
  {
    id: "SET-MYN-301",
    settlementBatchId: "MYN-DISB-SEP-01",
    marketplace: "Myntra",
    settlementDate: "2026-09-06",
    orderId: "ORD-1012",
    grossAmount: 1898,
    deductions: [
      { category: "COMMISSION", name: "Myntra Commission (15%)", amount: 284.7 },
      { category: "LOGISTICS", name: "Myntra Logistics Fulfillment", amount: 75 },
    ],
    tcsTdsTax: 18.98 + 1.9,
    netSettlement: 1517.42,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "CMS-KOTAK-44819",
  },
  {
    id: "SET-MYN-302",
    settlementBatchId: "MYN-DISB-SEP-02",
    marketplace: "Myntra",
    settlementDate: "2026-09-07",
    orderId: "ORD-1013",
    grossAmount: 1349,
    deductions: [
      { category: "COMMISSION", name: "Myntra Commission (14%)", amount: 188.86 },
      { category: "LOGISTICS", name: "Myntra Logistics Fulfillment", amount: 60 },
    ],
    tcsTdsTax: 13.49 + 1.35,
    netSettlement: 1085.3,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "CMS-KOTAK-44820",
  },
  {
    id: "SET-MSH-002",
    settlementBatchId: "MSH-PAY-0907",
    marketplace: "Meesho",
    settlementDate: "2026-09-07",
    orderId: "ORD-1014",
    grossAmount: 779,
    deductions: [
      { category: "COMMISSION", name: "0% Commission Promo", amount: 0 },
      { category: "LOGISTICS", name: "Meesho Logistics Fulfillment", amount: 45 },
    ],
    tcsTdsTax: 7.79 + 0.78,
    netSettlement: 725.43,
    reconciliationStatus: "RECONCILED",
    bankTxRef: "NEFT-ICICI-4413",
  },
];

export const INITIAL_PURCHASES: PurchaseBill[] = [
  {
    id: "PUR-2026-081",
    supplierId: "SUP-001",
    supplierName: "Apex Electronics Mfg Ltd",
    invoiceNumber: "APX-INV-9921",
    invoiceDate: "2026-08-01",
    sku: "ELEC-WEM-01",
    quantity: 100,
    unitCost: 380,
    taxes: 6840,
    totalAmount: 44840,
    paymentStatus: "PAID",
  },
  {
    id: "PUR-2026-082",
    supplierId: "SUP-002",
    supplierName: "Zenith Cable & Power Supplies",
    invoiceNumber: "ZPS-2026-440",
    invoiceDate: "2026-08-05",
    sku: "ELEC-USBC-65W",
    quantity: 50,
    unitCost: 420,
    taxes: 3780,
    totalAmount: 24780,
    paymentStatus: "PAID",
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: "EXP-101",
    date: "2026-09-01",
    category: "Software",
    description: "Shopify Advanced Subscription & Inventory Apps",
    amount: 7500,
    vendor: "Shopify Inc",
    paymentMethod: "CREDIT_CARD",
    isRecurring: true,
  },
  {
    id: "EXP-102",
    date: "2026-09-01",
    category: "Rent",
    description: "Warehouse & Packing Station Space Rent (Bhiwandi)",
    amount: 25000,
    vendor: "Kapadia Logistics Park",
    paymentMethod: "BANK_TRANSFER",
    isRecurring: true,
  },
  {
    id: "EXP-103",
    date: "2026-09-02",
    category: "Advertising",
    description: "Meta Ads (Facebook & Instagram D2C Conversion Campaign)",
    amount: 1250,
    vendor: "Meta Platforms Ireland",
    paymentMethod: "CREDIT_CARD",
    isRecurring: false,
    marketplace: "Personal Website",
    attributedSku: "ELEC-ANC-EB",
  },
  {
    id: "EXP-105",
    date: "2026-09-03",
    category: "Advertising",
    description: "Amazon Sponsored Products (PPC Manual Keyword Campaign)",
    amount: 950,
    vendor: "Amazon Advertising",
    paymentMethod: "CREDIT_CARD",
    isRecurring: false,
    marketplace: "Amazon India",
    attributedSku: "ELEC-WEM-01",
  },
  {
    id: "EXP-104",
    date: "2026-09-03",
    category: "Packaging",
    description: "Corrugated boxes, bubble wrap & security tamper tape",
    amount: 4800,
    vendor: "Shree Pack Industries",
    paymentMethod: "UPI",
    isRecurring: false,
  },
  {
    id: "EXP-106",
    date: "2026-09-04",
    category: "Advertising",
    description: "Flipkart Product Listing Ads (PLA Performance Campaign)",
    amount: 680,
    vendor: "Flipkart Internet Pvt Ltd",
    paymentMethod: "CREDIT_CARD",
    isRecurring: false,
    marketplace: "Flipkart",
    attributedSku: "ELEC-USBC-65W",
  },
  {
    id: "EXP-107",
    date: "2026-09-05",
    category: "Advertising",
    description: "Myntra Brand Booster Sponsored Placements",
    amount: 820,
    vendor: "Myntra Designs Pvt Ltd",
    paymentMethod: "CREDIT_CARD",
    isRecurring: false,
    marketplace: "Myntra",
    attributedSku: "ELEC-ANC-EB",
  },
  {
    id: "EXP-108",
    date: "2026-09-05",
    category: "Advertising",
    description: "Meesho Catalog Discovery Boost Ads",
    amount: 350,
    vendor: "Fashnear Technologies Pvt Ltd",
    paymentMethod: "UPI",
    isRecurring: false,
    marketplace: "Meesho",
    attributedSku: "ELEC-BRAID-CBL",
  },
];

export const INITIAL_AI_DOCUMENTS: AIStagedDocument[] = [
  {
    id: "DOC-AI-001",
    fileName: "Amazon_Tax_Invoice_402-8392182.pdf",
    fileType: "INVOICE",
    uploadDate: "2026-09-07T18:30:00Z",
    status: "STAGED_NEEDS_REVIEW",
    rawTextPreview: `TAX INVOICE
Sold By: VoltTech India Retail Pvt Ltd
Invoice Number: DEL-2026-09-881
Order ID: 402-8392182-1928301
Order Date: 02.09.2026
Channel: Amazon.in
Item: Wireless Ergonomic Mouse (Silent Click)
SKU: B08WEM01-IND
Qty: 1
Unit Price: ₹899.00
Discount: ₹50.00
IGST 18%: ₹129.50
Total: ₹849.00`,
    extractedData: {
      marketplace: { value: "Amazon India", confidence: 0.98, provenance: "AI_EXTRACTED" },
      orderId: { value: "402-8392182-1928301", confidence: 0.99, provenance: "AI_EXTRACTED" },
      invoiceNumber: { value: "DEL-2026-09-881", confidence: 0.95, provenance: "AI_EXTRACTED" },
      orderDate: { value: "2026-09-02", confidence: 0.94, provenance: "AI_EXTRACTED" },
      sku: { value: "ELEC-WEM-01", confidence: 0.92, provenance: "AI_EXTRACTED" },
      productName: { value: "Wireless Ergonomic Mouse (Silent Click)", confidence: 0.97, provenance: "AI_EXTRACTED" },
      quantity: { value: 1, confidence: 0.99, provenance: "AI_EXTRACTED" },
      unitPrice: { value: 899, confidence: 0.97, provenance: "AI_EXTRACTED" },
      discount: { value: 50, confidence: 0.91, provenance: "AI_EXTRACTED" },
      taxAmount: { value: 129.5, confidence: 0.93, provenance: "AI_EXTRACTED" },
      totalAmount: { value: 849, confidence: 0.98, provenance: "AI_EXTRACTED" },
    },
    arithmeticValidation: validateDocumentArithmetic(1, 899, 50, 0, 849),
    catalogValidation: {
      skuMatched: true,
      matchedSkuId: "ELEC-WEM-01",
    },
  },
  {
    id: "DOC-AI-002",
    fileName: "Zenith_Cable_Invoice_Scan_Corrupted.pdf",
    fileType: "SUPPLIER_BILL",
    uploadDate: "2026-09-07T19:15:00Z",
    status: "STAGED_NEEDS_REVIEW",
    rawTextPreview: `ZENITH CABLE & POWER SUPPLIES
Bill No: ZPS-9021
Date: 06-Sep-2026
Product: Braided 100W Type-C to Type-C Cable
Quantity: 100
Rate: ₹110.00
Subtotal: ₹11,000.00
Tax GST 18%: ₹1,980.00
Extracted Grand Total: ₹14,200.00 (Blurred handwritten smudge)`,
    extractedData: {
      marketplace: { value: "Personal Website", confidence: 0.75, provenance: "AI_EXTRACTED" },
      orderId: { value: "PO-ZPS-9021", confidence: 0.82, provenance: "AI_EXTRACTED" },
      invoiceNumber: { value: "ZPS-9021", confidence: 0.88, provenance: "AI_EXTRACTED" },
      orderDate: { value: "2026-09-06", confidence: 0.9, provenance: "AI_EXTRACTED" },
      sku: { value: "ELEC-BRAID-CBL", confidence: 0.86, provenance: "AI_EXTRACTED" },
      productName: { value: "Braided 100W Type-C to Type-C Cable (2m)", confidence: 0.91, provenance: "AI_EXTRACTED" },
      quantity: { value: 100, confidence: 0.95, provenance: "AI_EXTRACTED" },
      unitPrice: { value: 110, confidence: 0.92, provenance: "AI_EXTRACTED" },
      discount: { value: 0, confidence: 0.9, provenance: "AI_EXTRACTED" },
      taxAmount: { value: 1980, confidence: 0.89, provenance: "AI_EXTRACTED" },
      totalAmount: {
        value: 14200,
        confidence: 0.62,
        provenance: "AI_EXTRACTED",
        isFlaggedAnomaly: true,
        anomalyMessage: "Mathematical mismatch detected between line items and total.",
      },
    },
    arithmeticValidation: validateDocumentArithmetic(100, 110, 0, 1980, 14200),
    catalogValidation: {
      skuMatched: true,
      matchedSkuId: "ELEC-BRAID-CBL",
    },
  },
];

export const INITIAL_AUDIT_LOGS: FinancialAuditLog[] = [
  {
    id: "AUD-001",
    timestamp: "2026-09-07T14:20:00Z",
    entityType: "PRODUCT_COST",
    entityId: "ELEC-WEM-01",
    fieldName: "currentCostPrice",
    oldValue: "₹350",
    newValue: "₹380",
    modifiedBy: "Rajesh (Finance Lead)",
    reason: "Supplier raw material component revision for Q3 batch",
    sourceDocumentId: "PUR-2026-081",
  },
  {
    id: "AUD-002",
    timestamp: "2026-09-06T11:10:00Z",
    entityType: "CLAIM",
    entityId: "CLM-301",
    fieldName: "amountRecovered",
    oldValue: "₹0",
    newValue: "₹650",
    modifiedBy: "Sneha (Ops Manager)",
    reason: "SAFE-T claim approval received from Amazon India seller support",
    sourceDocumentId: "DOC-SAFE-T-405.pdf",
  },
];

export const INITIAL_COMPLAINTS: CustomerComplaint[] = [
  {
    id: "TKT-1001",
    ticketNumber: "MF-TKT-8821",
    customerName: "Aakash Singhania",
    customerEmail: "aakash.singh@gmail.com",
    customerPhone: "+91 98112 44321",
    orderId: "ORD-0994",
    channelOrderId: "OD8839201928410294",
    marketplace: "Flipkart",
    sku: "ELEC-USBC-65W",
    category: "DAMAGED_PRODUCT",
    priority: "HIGH",
    status: "OPEN",
    subject: "Charger port pin bent upon arrival",
    description: "The parcel arrived with outer seal torn. Upon opening, one of the dual Type-C ports was bent and not connecting.",
    createdAt: "2026-09-18T10:30:00Z",
  },
  {
    id: "TKT-1002",
    ticketNumber: "MF-TKT-8822",
    customerName: "Pooja Hegde",
    customerEmail: "pooja.hegde@outlook.com",
    customerPhone: "+91 97410 88219",
    orderId: "ORD-0995",
    channelOrderId: "408-1928301-4491029",
    marketplace: "Amazon India",
    sku: "ELEC-WEM-01",
    category: "DEFECTIVE_PRODUCT",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    subject: "Mouse scroll wheel clicking intermittently",
    description: "The mouse pairs successfully via 2.4G dongle, but the middle wheel click misses 50% of the time.",
    createdAt: "2026-09-19T14:15:00Z",
  },
  {
    id: "TKT-1003",
    ticketNumber: "MF-TKT-8823",
    customerName: "Karthik Nair",
    customerEmail: "karthik.nair@yahoo.com",
    customerPhone: "+91 94471 00293",
    orderId: "ORD-0996",
    channelOrderId: "MSH-SUB-8819204",
    marketplace: "Meesho",
    sku: "ELEC-BRAID-CBL",
    category: "DELIVERY_DELAY",
    priority: "LOW",
    status: "RESOLVED",
    subject: "Courier tracking stuck at regional hub for 5 days",
    description: "Shipment was held up at Bhiwandi sorting facility. Expedited with Delhivery dispatch team.",
    createdAt: "2026-09-15T09:00:00Z",
    resolvedAt: "2026-09-17T16:40:00Z",
    resolutionNotes: "Delhivery escalations cleared the regional hub backlog; package successfully delivered and signed for.",
  },
];

export const DEFAULT_ACCOUNTS: UserAccount[] = [
  {
    id: "ACC-001",
    name: "Ujjaval",
    email: "ujjaval@brand.in",
    accountType: "BRAND_OWNER",
    companyName: "VoltTech Consumer Electronics",
    gstin: "27AABCV1234F1Z1",
    phone: "+91 98200 99881",
    authenticatedAt: "2026-09-24T08:00:00Z",
  },
  {
    id: "ACC-002",
    name: "Rajesh Sharma (Apex)",
    email: "rajesh@apexelectronics.in",
    accountType: "SUPPLIER",
    supplierId: "SUP-001",
    companyName: "Apex Electronics Mfg Ltd",
    gstin: "27AAACA1234A1Z5",
    phone: "+91 98200 12345",
    authenticatedAt: "2026-09-24T08:30:00Z",
  },
  {
    id: "ACC-003",
    name: "Metro Retail Distribution",
    email: "orders@metrodistributors.com",
    accountType: "WHOLESALER",
    companyName: "Metro B2B Wholesalers & Logistics",
    gstin: "24AABCM9981K1Z3",
    phone: "+91 99120 44556",
    authenticatedAt: "2026-09-24T09:00:00Z",
  },
];
