"use client";

import React, { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { X, Copy, Check, TrendingUp, AlertTriangle, ShieldCheck, BookmarkCheck } from "lucide-react";
import { formatINR, formatPercent } from "@/lib/utils";

export interface SkuEconomicsItem {
  sku: string;
  productName: string;
  unitsSold: number;
  revenue: number;
  cogs: number;
  marketplaceCharges: number;
  returnLosses: number;
  profit: number;
  margin: number;
  adSpend?: number;
  poas?: number;
  returnRate: number;
}

export interface SkuDrawerProps {
  skuData: SkuEconomicsItem | null;
  onClose: () => void;
  isAcknowledgedLossLeader?: boolean;
  onToggleLossLeader?: (sku: string) => void;
}

export function SkuDrawer({
  skuData,
  onClose,
  isAcknowledgedLossLeader = false,
  onToggleLossLeader,
}: SkuDrawerProps) {
  const [mounted, setMounted] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setMounted(true);
    return () => setMounted(false);
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  if (!skuData || !mounted) return null;

  const realizedUnitPrice = Math.round(skuData.revenue / (skuData.unitsSold || 1));
  const unitCogs = Math.round(skuData.cogs / (skuData.unitsSold || 1));
  const unitMarketplace = Math.round(skuData.marketplaceCharges / (skuData.unitsSold || 1));
  const unitReturnLoss = Math.round(skuData.returnLosses / (skuData.unitsSold || 1));
  const unitProfit = Math.round(skuData.profit / (skuData.unitsSold || 1));

  const handleCopySummary = async () => {
    const summaryText = [
      `=== SKU FINANCIAL & UNIT ECONOMICS SUMMARY ===`,
      `SKU: ${skuData.sku}`,
      `Product: ${skuData.productName}`,
      `Financial Status: ${skuData.profit >= 0 ? "Profitable" : "Loss-Making"}`,
      ``,
      `--- Volume & Overall Economics ---`,
      `• Units Sold: ${skuData.unitsSold} units`,
      `• Net Revenue: ${formatINR(skuData.revenue)}`,
      `• Total COGS: ${formatINR(skuData.cogs)}`,
      `• Marketplace Charges: -${formatINR(skuData.marketplaceCharges)}`,
      `• Return & RTO Losses: -${formatINR(skuData.returnLosses)}`,
      `• Net Contribution Profit: ${formatINR(skuData.profit)}`,
      `• Contribution Margin: ${formatPercent(skuData.margin)}`,
      ``,
      `--- Per-Unit Economics Waterfall (1 Item) ---`,
      `• Realized Unit Price: ${formatINR(realizedUnitPrice)}`,
      `• Unit Product Cost (COGS): -${formatINR(unitCogs)}`,
      `• Marketplace Fees & Logistics: -${formatINR(unitMarketplace)}`,
      `• Reverse Logistics & Return Drag: -${formatINR(unitReturnLoss)}`,
      `• Net Unit Profit: ${formatINR(unitProfit)} / unit`,
      ``,
      `--- Marketing & Logistics Health ---`,
      `• Return & RTO Rate: ${formatPercent(skuData.returnRate)}`,
      `• POAS / Advertising: ${skuData.poas !== undefined ? `${skuData.poas}x` : "No Direct Ads"}`,
      skuData.adSpend ? `• Direct Ad Spend: ${formatINR(skuData.adSpend)}` : null,
      ``,
      `Generated by MarginFlow Financial Intelligence`,
    ].filter(Boolean).join("\n");

    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(summaryText);
      } else {
        const textArea = document.createElement("textarea");
        textArea.value = summaryText;
        textArea.style.position = "fixed";
        textArea.style.opacity = "0";
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error("Failed to copy SKU summary:", err);
    }
  };

  return createPortal(
    <div
      className="fixed inset-0 z-50 bg-black/30 backdrop-blur-xs flex justify-end animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg bg-white/95 backdrop-blur-xl h-full shadow-apple-lg border-l border-black/[0.08] flex flex-col p-6 overflow-y-auto animate-in slide-in-from-right duration-300"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Drawer Header */}
        <div className="flex items-start justify-between pb-4 border-b border-black/[0.06]">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[11px] font-semibold px-2.5 py-0.5 rounded-full bg-[#0071E3]/10 text-[#0071E3] border border-[#0071E3]/20">
                Unit economics inspection
              </span>
              <span
                className={`text-[11px] font-semibold px-2.5 py-0.5 rounded-full border ${
                  skuData.profit >= 0
                    ? "bg-[#288548]/10 text-[#288548] border-[#288548]/20"
                    : isAcknowledgedLossLeader
                    ? "bg-amber-500/10 text-amber-800 border-amber-500/20"
                    : "bg-[#D70015]/10 text-[#D70015] border-[#D70015]/20"
                }`}
              >
                {skuData.profit >= 0
                  ? "Profitable"
                  : isAcknowledgedLossLeader
                  ? "Loss leader (acknowledged)"
                  : "Loss-making"}
              </span>
            </div>
            <h3 className="text-xl font-bold text-[#1D1D1F] mt-2 font-mono tracking-tight">{skuData.sku}</h3>
            <p className="text-xs text-[#86868B] mt-0.5 font-medium leading-relaxed">{skuData.productName}</p>
          </div>
          <button
            onClick={onClose}
            aria-label="Close drawer"
            className="w-8 h-8 rounded-full bg-[#F5F5F7] hover:bg-[#E8E8ED] flex items-center justify-center text-[#86868B] hover:text-[#1D1D1F] transition cursor-pointer shrink-0"
            title="Close drawer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Quick Metrics Grid */}
        <div className="grid grid-cols-2 gap-3 my-5">
          <div className="apple-card p-4 rounded-2xl shadow-apple-sm">
            <span className="text-[11px] text-[#86868B] font-medium">Net revenue</span>
            <div className="text-lg font-bold text-[#1D1D1F] mt-0.5 tracking-tight tabular-nums">
              {formatINR(skuData.revenue)}
            </div>
            <span className="text-[11px] text-[#86868B] font-medium tabular-nums">{skuData.unitsSold} units sold</span>
          </div>
          <div className="apple-card p-4 rounded-2xl shadow-apple-sm">
            <span className="text-[11px] text-[#86868B] font-medium">Contribution margin</span>
            <div
              className={`text-lg font-bold mt-0.5 tracking-tight tabular-nums ${
                skuData.profit >= 0 ? "text-[#288548]" : "text-[#D70015]"
              }`}
            >
              {formatPercent(skuData.margin)}
            </div>
            <span className="text-[11px] text-[#86868B] font-medium tabular-nums">{formatINR(skuData.profit)} net</span>
          </div>
        </div>

        {/* Per-Unit Economics Step-Down Waterfall */}
        <div className="apple-card rounded-2xl p-4.5 mb-5 shadow-apple-sm">
          <h4 className="text-xs font-bold text-[#1D1D1F] tracking-tight mb-3.5">
            Unit economics breakdown (per 1 item)
          </h4>
          <div className="space-y-3 text-xs">
            <div className="flex items-center justify-between pb-2 border-b border-black/[0.06]">
              <span className="text-[#6E6E73] font-medium">Average realized unit price</span>
              <span className="font-semibold text-[#1D1D1F] tabular-nums">
                {formatINR(realizedUnitPrice)}
              </span>
            </div>
            <div className="flex items-center justify-between text-[#6E6E73]">
              <span>− Unit product cost (COGS)</span>
              <span className="text-[#1D1D1F] font-semibold tabular-nums">-{formatINR(unitCogs)}</span>
            </div>
            <div className="flex items-center justify-between text-[#6E6E73]">
              <span>− Marketplace fees &amp; logistics</span>
              <span className="text-[#D70015] font-semibold tabular-nums">-{formatINR(unitMarketplace)}</span>
            </div>
            <div className="flex items-center justify-between text-[#6E6E73]">
              <span>− Reverse logistics &amp; return drag</span>
              <span className="text-[#B25E00] font-semibold tabular-nums">
                {skuData.returnLosses > 0 ? `-${formatINR(unitReturnLoss)}` : "₹0"}
              </span>
            </div>
            <div className="flex items-center justify-between pt-2.5 border-t border-black/[0.06]">
              <span className="text-[#1D1D1F] font-bold">Net unit contribution profit</span>
              <span
                className={`text-sm font-bold tabular-nums ${
                  skuData.profit >= 0 ? "text-[#288548]" : "text-[#D70015]"
                }`}
              >
                {formatINR(unitProfit)}
              </span>
            </div>
          </div>
        </div>

        {/* Performance Indicators */}
        <div className="space-y-3 mb-6">
          <div className="apple-card p-3.5 rounded-2xl shadow-apple-sm flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-[#1D1D1F]">POAS / advertising drag</div>
              <div className="text-[11px] text-[#86868B] mt-0.5 font-medium tabular-nums">
                Ad spend: {skuData.adSpend ? formatINR(skuData.adSpend) : "₹0"}
              </div>
            </div>
            <div>
              {skuData.poas !== undefined ? (
                <span
                  className={`px-3 py-1 rounded-full text-xs font-semibold tabular-nums ${
                    skuData.poas >= 1.0 ? "bg-[#288548]/10 text-[#288548] border border-[#288548]/20" : "bg-[#B25E00]/10 text-[#B25E00] border border-[#B25E00]/20"
                  }`}
                >
                  {skuData.poas}x POAS
                </span>
              ) : (
                <span className="text-xs text-[#86868B] font-medium">No direct ads</span>
              )}
            </div>
          </div>

          <div className="apple-card p-3.5 rounded-2xl shadow-apple-sm flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-[#1D1D1F]">Return &amp; RTO rate</div>
              <div className="text-[11px] text-[#86868B] mt-0.5 font-medium tabular-nums">
                Total return losses: {formatINR(skuData.returnLosses)}
              </div>
            </div>
            <div>
              <span
                className={`px-3 py-1 rounded-full text-xs font-semibold tabular-nums border ${
                  skuData.returnRate > 0.2
                    ? "bg-[#D70015]/10 text-[#D70015] border-[#D70015]/20"
                    : "bg-[#288548]/10 text-[#288548] border-[#288548]/20"
                }`}
              >
                {formatPercent(skuData.returnRate)}
              </span>
            </div>
          </div>
        </div>

        {/* Action Footer */}
        <div className="mt-auto pt-4 border-t border-black/[0.06] flex flex-col gap-2.5">
          {skuData.profit < 0 && onToggleLossLeader && (
            <button
              type="button"
              onClick={() => onToggleLossLeader(skuData.sku)}
              className={`w-full py-2.5 px-4 text-xs font-semibold rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer shadow-apple-sm btn-press ${
                isAcknowledgedLossLeader
                  ? "bg-amber-500/10 hover:bg-amber-500/15 text-amber-800 border border-amber-500/25"
                  : "bg-[#1D1D1F] hover:bg-black text-white"
              }`}
              title={
                isAcknowledgedLossLeader
                  ? "Remove Loss Leader acknowledgment"
                  : "Acknowledge as Loss Leader to exclude from Margin Erosion Advisory"
              }
            >
              <BookmarkCheck className="w-3.5 h-3.5" />
              <span>
                {isAcknowledgedLossLeader
                  ? "Acknowledged as Loss Leader (Click to Revoke)"
                  : "Acknowledge / Mark as Loss Leader"}
              </span>
            </button>
          )}

          <div className="flex gap-2.5">
            <button
              type="button"
              onClick={handleCopySummary}
              className={`flex-1 py-2.5 px-4 text-xs font-medium rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer shadow-apple-sm btn-press ${
                copied
                  ? "bg-[#288548]/10 border border-[#288548]/20 text-[#288548]"
                  : "bg-[#F5F5F7] hover:bg-[#E8E8ED] text-[#1D1D1F] border border-black/[0.06]"
              }`}
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-[#288548] shrink-0" />
                  <span>Copied to clipboard</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-[#6E6E73] shrink-0" />
                  <span>Copy SKU summary</span>
                </>
              )}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="py-2.5 px-6 bg-[#F5F5F7] hover:bg-[#E8E8ED] text-[#1D1D1F] border border-black/[0.06] text-xs font-medium rounded-xl transition shadow-apple-sm btn-press cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>,
    document.body
  );
}
