"use client";

import React, { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { X, Copy, Check, TrendingUp, AlertTriangle, ShieldCheck } from "lucide-react";
import { formatINR, formatPercent } from "@/lib/utils";

export interface SkuEconomicsItem {
  sku: string;
  productName: string;
  unitsSold: number;
  revenue: number;
  cogs: number;
  marketplaceCharges: number;
  returnLosses: number;
  profit: number;
  margin: number;
  adSpend?: number;
  poas?: number;
  returnRate: number;
}

export interface SkuDrawerProps {
  skuData: SkuEconomicsItem | null;
  onClose: () => void;
}

export function SkuDrawer({ skuData, onClose }: SkuDrawerProps) {
  const [mounted, setMounted] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setMounted(true);
    return () => setMounted(false);
  }, []);

  if (!skuData || !mounted) return null;

  const realizedUnitPrice = Math.round(skuData.revenue / (skuData.unitsSold || 1));
  const unitCogs = Math.round(skuData.cogs / (skuData.unitsSold || 1));
  const unitMarketplace = Math.round(skuData.marketplaceCharges / (skuData.unitsSold || 1));
  const unitReturnLoss = Math.round(skuData.returnLosses / (skuData.unitsSold || 1));
  const unitProfit = Math.round(skuData.profit / (skuData.unitsSold || 1));

  const handleCopySummary = async () => {
    const summaryText = [
      `=== SKU FINANCIAL & UNIT ECONOMICS SUMMARY ===`,
      `SKU: ${skuData.sku}`,
      `Product: ${skuData.productName}`,
      `Financial Status: ${skuData.profit >= 0 ? "Profitable" : "Loss-Making"}`,
      ``,
      `--- Volume & Overall Economics ---`,
      `• Units Sold: ${skuData.unitsSold} units`,
      `• Net Revenue: ${formatINR(skuData.revenue)}`,
      `• Total COGS: ${formatINR(skuData.cogs)}`,
      `• Marketplace Charges: -${formatINR(skuData.marketplaceCharges)}`,
      `• Return & RTO Losses: -${formatINR(skuData.returnLosses)}`,
      `• Net Contribution Profit: ${formatINR(skuData.profit)}`,
      `• Contribution Margin: ${formatPercent(skuData.margin)}`,
      ``,
      `--- Per-Unit Economics Waterfall (1 Item) ---`,
      `• Realized Unit Price: ${formatINR(realizedUnitPrice)}`,
      `• Unit Product Cost (COGS): -${formatINR(unitCogs)}`,
      `• Marketplace Fees & Logistics: -${formatINR(unitMarketplace)}`,
      `• Reverse Logistics & Return Drag: -${formatINR(unitReturnLoss)}`,
      `• Net Unit Profit: ${formatINR(unitProfit)} / unit`,
      ``,
      `--- Marketing & Logistics Health ---`,
      `• Return & RTO Rate: ${formatPercent(skuData.returnRate)}`,
      `• POAS / Advertising: ${skuData.poas !== undefined ? `${skuData.poas}x` : "No Direct Ads"}`,
      skuData.adSpend ? `• Direct Ad Spend: ${formatINR(skuData.adSpend)}` : null,
      ``,
      `Generated by MarginFlow Financial Intelligence`,
    ].filter(Boolean).join("\n");

    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(summaryText);
      } else {
        const textArea = document.createElement("textarea");
        textArea.value = summaryText;
        textArea.style.position = "fixed";
        textArea.style.opacity = "0";
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error("Failed to copy SKU summary:", err);
    }
  };

  return createPortal(
    <div
      className="fixed inset-0 z-50 drawer-backdrop flex justify-end animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg bg-white h-full shadow-2xl flex flex-col p-6 overflow-y-auto animate-in slide-in-from-right duration-300"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Drawer Header */}
        <div className="flex items-start justify-between pb-4 border-b border-slate-100">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200">
                Unit Economics Inspection
              </span>
              <span
                className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full border ${
                  skuData.profit >= 0
                    ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                    : "bg-rose-50 text-rose-700 border-rose-200"
                }`}
              >
                {skuData.profit >= 0 ? "Profitable" : "Loss-Making"}
              </span>
            </div>
            <h3 className="text-xl font-bold text-slate-900 mt-2 font-mono tracking-tight">{skuData.sku}</h3>
            <p className="text-xs text-slate-500 mt-0.5 font-medium leading-relaxed">{skuData.productName}</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 flex items-center justify-center text-slate-500 hover:text-slate-800 transition cursor-pointer shrink-0"
            title="Close Drawer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Quick Metrics Grid */}
        <div className="grid grid-cols-2 gap-3 my-5">
          <div className="bg-slate-50/80 p-4 rounded-2xl border border-slate-200/70">
            <span className="text-[11px] text-slate-400 font-medium">Net Revenue</span>
            <div className="text-lg font-bold text-[#1D1D1F] mt-0.5 tracking-tight tabular-nums">
              {formatINR(skuData.revenue)}
            </div>
            <span className="text-[11px] text-slate-500 font-medium">{skuData.unitsSold} units sold</span>
          </div>
          <div className="bg-slate-50/80 p-4 rounded-2xl border border-slate-200/70">
            <span className="text-[11px] text-slate-400 font-medium">Contribution Margin</span>
            <div
              className={`text-lg font-bold mt-0.5 tracking-tight tabular-nums ${
                skuData.profit >= 0 ? "text-[#288548]" : "text-[#D70015]"
              }`}
            >
              {formatPercent(skuData.margin)}
            </div>
            <span className="text-[11px] text-slate-500 font-medium">{formatINR(skuData.profit)} net</span>
          </div>
        </div>

        {/* Per-Unit Economics Step-Down Waterfall */}
        <div className="bg-white rounded-2xl border border-slate-200 p-4.5 mb-5 shadow-xs">
          <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-3.5">
            Unit Economics Breakdown (Per 1 Item)
          </h4>
          <div className="space-y-3 text-xs">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-slate-600 font-medium">Average Realized Unit Price</span>
              <span className="font-semibold text-slate-900 font-mono tabular-nums">
                {formatINR(realizedUnitPrice)}
              </span>
            </div>
            <div className="flex items-center justify-between text-slate-600">
              <span>− Unit Product Cost (COGS)</span>
              <span className="font-mono text-slate-800 font-semibold tabular-nums">-{formatINR(unitCogs)}</span>
            </div>
            <div className="flex items-center justify-between text-slate-600">
              <span>− Marketplace Fees &amp; Logistics</span>
              <span className="font-mono text-rose-600 font-semibold tabular-nums">-{formatINR(unitMarketplace)}</span>
            </div>
            <div className="flex items-center justify-between text-slate-600">
              <span>− Reverse Logistics &amp; Return Drag</span>
              <span className="font-mono text-amber-600 font-semibold tabular-nums">
                {skuData.returnLosses > 0 ? `-${formatINR(unitReturnLoss)}` : "₹0"}
              </span>
            </div>
            <div className="flex items-center justify-between pt-2.5 border-t border-slate-200">
              <span className="text-slate-900 font-bold">Net Unit Contribution Profit</span>
              <span
                className={`font-mono text-sm font-bold tabular-nums ${
                  skuData.profit >= 0 ? "text-emerald-700" : "text-rose-600"
                }`}
              >
                {formatINR(unitProfit)}
              </span>
            </div>
          </div>
        </div>

        {/* Performance Indicators */}
        <div className="space-y-3 mb-6">
          <div className="p-3.5 rounded-2xl border border-slate-200 bg-slate-50/60 flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-slate-800">POAS / Advertising Drag</div>
              <div className="text-[11px] text-slate-500 mt-0.5 font-medium">
                Ad Spend: {skuData.adSpend ? formatINR(skuData.adSpend) : "₹0"}
              </div>
            </div>
            <div>
              {skuData.poas !== undefined ? (
                <span
                  className={`px-3 py-1 rounded-full text-xs font-bold ${
                    skuData.poas >= 1.0 ? "bg-emerald-100 text-emerald-800 border border-emerald-200" : "bg-amber-100 text-amber-800 border border-amber-200"
                  }`}
                >
                  {skuData.poas}x POAS
                </span>
              ) : (
                <span className="text-xs text-slate-400 font-medium">No Direct Ads</span>
              )}
            </div>
          </div>

          <div className="p-3.5 rounded-2xl border border-slate-200 bg-slate-50/60 flex items-center justify-between">
            <div>
              <div className="text-xs font-bold text-slate-800">Return &amp; RTO Rate</div>
              <div className="text-[11px] text-slate-500 mt-0.5 font-medium">
                Total Return Losses: {formatINR(skuData.returnLosses)}
              </div>
            </div>
            <div>
              <span
                className={`px-3 py-1 rounded-full text-xs font-bold border ${
                  skuData.returnRate > 0.2
                    ? "bg-rose-50 text-rose-700 border-rose-200"
                    : "bg-emerald-50 text-emerald-700 border-emerald-200"
                }`}
              >
                {formatPercent(skuData.returnRate)}
              </span>
            </div>
          </div>
        </div>

        {/* Action Footer */}
        <div className="mt-auto pt-4 border-t border-slate-100 flex gap-2.5">
          <button
            type="button"
            onClick={handleCopySummary}
            className={`flex-1 py-2.5 px-4 text-xs font-semibold rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer active:scale-[0.99] ${
              copied
                ? "bg-emerald-50 border border-emerald-300 text-emerald-800 shadow-xs"
                : "bg-slate-100 hover:bg-slate-200/80 text-slate-800 border border-slate-200/70"
            }`}
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-600 shrink-0" />
                <span>Copy SKU Summary</span>
              </>
            )}
          </button>
          <button
            type="button"
            onClick={onClose}
            className="py-2.5 px-6 bg-slate-900 hover:bg-black active:scale-[0.99] text-white text-xs font-semibold rounded-xl transition shadow-xs cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}
